services:
  server:
    container_name: server
    restart: always
    build:
      context: ./be.socialnet
      dockerfile: ./docker/Dockerfile
    working_dir: /var/www/html
    ports:
      - "8000:80"
    volumes:
      - ./be.socialnet:/var/www/html
      - ./be.socialnet/docker/nginx_log:/var/log/nginx
      - ./be.socialnet/docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./be.socialnet/docker/conf/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - mysql

  client:
    container_name: client
    restart: always
    build:
      context: ./fe.socialnet
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./fe.socialnet:/app

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./be.socialnet/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hungpv
      MYSQL_DATABASE: socialnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: hungpv
    ports:
      - "8080:80"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./be.socialnet:/var/www/html

  laravel_echo_server:
    image: oanhnn/laravel-echo-server
    restart: always
    container_name: laravel_echo_server
    ports:
      - "6001:6001"
